version: '3'
services:
  corspat_db:
    image: postgres
    env_file:
      - ./app/.env
    ports:
      - 5432:5432
  corspat_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - corspat_db