CREATE TABLE users (
 id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 email VARCHAR,
 hash VARCHAR,
 first_name VARCHAR,
 last_name VARCHAR,
 is_checked BOOLEAN,
 created_at VARCHAR
);

CREATE TABLE path (
 user_id INT,
 course_uuid VARCHAR,
 course_domain VARCHAR,
 course_url VARCHAR,
 course_title VARCHAR,
 course_desc VARCHAR,
 course_img VARCHAR,
 finished BOOLEAN,
 created_at VARCHAR
);

CREATE TABLE timetracker (
 user_id INT,
 course_uuid VARCHAR,
 course_domain VARCHAR,
 course_title VARCHAR,
 started_at VARCHAR,
 finished_at VARCHAR,
 duration VARCHAR,
 track_uuid VARCHAR
);

CREATE TABLE alerts (
 alert_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 alert_msg VARCHAR,
 alert_urgency INT,
 alert_link VARCHAR,
 created_at VARCHAR
);
